apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo
  labels:
    app: phpinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpinfo
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
      - name: phpinfo
        image: docker.artron.net/phpinfo:<BUILD_TAG>
        ports:
        - containerPort: 80
